/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
//  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//
//  // But you can create a sidebar manually
//  /*
//  tutorialSidebar: [
//    'intro',
//    'hello',
//    {
//      type: 'category',
//      label: 'Tutorial',
//      items: ['tutorial-basics/create-a-document'],
//    },
//  ],
//   */
//};

//export default sidebars;
export default {
    featuresSidebar: [
        {
            '🔥 新版本介绍': [
                'features/4.1',
                'features/4',
                'features/3'
            ],
        },
        'features/features',
        {
            '🌟 特性演示': [
                'features/features_demos/requests',
                'features/features_demos/selenium',
                'features/features_demos/change_mode',
                'features/features_demos/get_ele_attr',
                'features/features_demos/download',
            ]
        }
    ],
    usageSidebar: [{
        '🚀 控制浏览器': [
            'browser_control/introduction',
            'browser_control/connect_browser',
            'browser_control/browser_options',
            'browser_control/browser_object',
            'browser_control/visit',
            'browser_control/page_operation',
            'browser_control/get_page_info',
            {
                '🔎 查找元素': [
                    'browser_control/get_elements/intro',
                    'browser_control/get_elements/syntax',
                    'browser_control/get_elements/find_in_object',
                    'browser_control/get_elements/relative',
                    'browser_control/get_elements/behavior',
                    'browser_control/get_elements/filter',
                    'browser_control/get_elements/simplify',
                    'browser_control/get_elements/sheet']
            },
            'browser_control/ele_operation',
            'browser_control/get_ele_info',
            'browser_control/iframe',
            'browser_control/actions',
            'browser_control/mode_change',
            'browser_control/waiting',
            'browser_control/listener',
            'browser_control/console',
            'browser_control/screen',
            'browser_control/upload',
            'browser_control/pages',
        ],
        '🛫 SessionPage': [
            'SessionPage/intro',
            'SessionPage/create_obj',
            'SessionPage/visit',
            'SessionPage/get_page_info',
            'SessionPage/get_ele',
            'SessionPage/get_ele_info',
            'SessionPage/page_settings',
            'SessionPage/session_opt'
        ],
        '🧰 进阶使用': [
            {
                '⬇️ 下载文件': [
                    'download/intro',
                    'download/DownloadKit',
                    'download/browser'],
            },
            'advance/ini',
            'advance/settings',
            'advance/commands',
            'advance/errors',
            'advance/accelerate',
            'advance/packaging',
            'advance/tools',
            'advance/docking'],
    }, //'MixPage/intro'
    ],
    startSidebar: [
        'get_start/installation',
        'get_start/import',
        'get_start/before_start',
        {
            '🌏 上手示例': [
                'get_start/examples/control_browser',
                'get_start/examples/data_packets',
                'get_start/examples/switch_mode'
            ],
        },
        'get_start/concept'
    ],
    demoSidebar: [
        'tutorials/xingqiu',
        'tutorials/QandA',
        {
            '🥬 功能示例': [
                'tutorials/functions/new_browser',
                'tutorials/functions/create_browsers',
                'tutorials/functions/tabs',
                'tutorials/functions/headless',
                'tutorials/functions/set_cookies'
            ],
        },
        {
            '🍔 实战示例': [
                'tutorials/actual/multithread',
                'tutorials/actual/multi_browsers',
                'tutorials/actual/downloadQQ',
                'tutorials/actual/gitee',
                'tutorials/actual/maoyan',
                'tutorials/actual/starbucks',
                'tutorials/actual/douban',
                {
                    type: 'link',
                    label: '🥗 巡检自动上报(网友投稿)',
                    href: 'https://www.toutiao.com/article/7290179565996343847/'
                }],
        },
        {
            '🎬 教学视频': [
                {
                    type: 'link',
                    label: '🔊 dp 作者视频',
                    href: 'https://space.bilibili.com/20526000'
                },
                {
                    type: 'link',
                    label: '🔊 时一姐视频',
                    href: 'https://space.bilibili.com/308704191/channel/collectiondetail?sid=1947582'
                },
                {
                    type: 'link',
                    label: '🔊 骚神视频',
                    href: 'https://www.bilibili.com/video/BV1Km411d783'
                }],
        },
    ],
    versionsSidebar: [
        'versions/4.1.x',
        'versions/4.0.x',
        'versions/3x',
        'versions/2x',
        'versions/1x',
        'versions/next',
        'versions/statement',]
};